server:
  port: 8082

spring:
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: create
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #format_sql: TRUE

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/prototype?characterEncoding=utf8
    username: your DB username
    password: your DB password

  # ===============================
  # = SPRING DATA REST CONFIG
  # ===============================
  data:
    rest:
      base-path: api

# Disable the default loggers
#logging:
#  level:
#    org: WARN

### Show SQL executed with parameter bindings
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor: TRACE
#      springframework: DEBUG

# ===============================
# = JWT config
# ===============================
jwt:
  route:
    register: /api/auth/register
    login: /api/auth/login
    refresh: /api/auth/refresh
  tokenExpirationTime: 120 # Number of minutes
  refreshTokenExpTime:  4320 # Minutes
  tokenIssuer: https://prototype.whiletrue.cc
  tokenSigningKey: keyOnYouChoice
